apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  type: ClusterIP
  ports:
  - name: "5432"
    port: 5432 # POD port
    targetPort: 5432 # Container port
  selector:
    io.kompose.service: db