apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: frontend
    spec:
      containers:
      - image: ernezdocker/springboot-angular7-online-shopping-store_frontend:0.0.1-SNAPSHOT
        name: frontend
        ports:
        - containerPort: 80
      restartPolicy: Always
