apiVersion: skaffold/v1beta15
kind: Config
build:
  tagPolicy:
    sha256: {}
  # defines where to find the code at build time and where to push the resulting image
  artifacts:
    - image: springboot-angular7-online-shopping-store_backend
      # To learn more about how Jib builds Java containers visit
      # https://github.com/GoogleContainerTools/jib
      jib:
        project: backend
    - image: springboot-angular7-online-shopping-store_frontend
      jib:
        project: frontend
# defines the Kubernetes manifests to deploy on each run
deploy:
  kubectl:
    manifests:
      - ./kubernetes-manifests/*.persistentvolumeclaim.yaml
      - ./kubernetes-manifests/*.deployment.yaml
      - ./kubernetes-manifests/*.service.yaml
profiles:
# use the cloudbuild profile to build images using Google Cloud Build
- name: cloudbuild
  build:
    googleCloudBuild: {}
# use the dockerfile profile to build images using Docker instead of Jib
- name: dockerfile
  build:
    artifacts:
      - image: springboot-angular7-online-shopping-store_backend
        context: backend
      - image: springboot-angular7-online-shopping-store_frontend
        context: frontend
